
#include "bleapi.h"
#include "mbunit.h"
#include "adc.h"
#include "mbqueue.h"
#include "mi2c.h"


#define CYTOUCH_PASS    111111


/*************************Variables Declaration*********************************/
/* Externs */
extern mbdev_t *prv;
extern cydata_t DevData;
extern _portdat MbPort;
extern struct _adc AdcData;

extern bool TSetUpdateRequireBit;
extern bool FanSpeedUpdateRequireBit;
extern bool BoostUpdateRequireBit;


/* Globals */
const SERVICE_DEVICE_INFO_T CyTouchInfo = { "Ventmatika", "CyTouch", "123456", "1.0", "1.0" };

CYTOUCH_CONTROL_T CyTouchControl;

bool DeviceConnected = false;        // This flag is set when a Central device is connected
bool BLEStackStatus = false;         // Variable store the BLE stack status
bool BleDataPrepareRequired = false;
bool ChangeUartSettingsRequired = false;
bool PrvSettingsUpdateRequireBit = false;
//bool AuthKeyRequired = false;

/* MTU size to be used by Client and Server after MTU exchange */
uint16_t mtuSize = CYBLE_GATT_MTU;

/* Statics */
static uint8_t RxDataNotificationEnabled = NOTIFICATON_DISABLED;        //This flag is set when the Central device writes to CCCD to enable RxData notification
static uint8_t AlarmsNotificationEnabled = NOTIFICATON_DISABLED;        //This flag is set when the Central device writes to CCCD to enable Alarms notification
static uint8_t CyTouchErrorNotificationEnabled = NOTIFICATON_DISABLED;  //This flag is set when the Central device writes to CCCD to enable Errors notification


static CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
static CYBLE_GAP_CONN_UPDATE_PARAM_T ConnectionParametersHandle = {
    CONN_PARAM_UPDATE_MIN_CONN_INTERVAL, 
    CONN_PARAM_UPDATE_MAX_CONN_INTERVAL,
    CONN_PARAM_UPDATE_SLAVE_LATENCY, 
    CONN_PARAM_UPDATE_SUPRV_TIMEOUT
}; //Connection Parameter update values

/* Static functions */
static CYBLE_API_RESULT_T UpdateCCCDAttribute( CYBLE_GATT_DB_ATTR_HANDLE_T handle, uint8_t ntf, uint8_t ind );
static CYBLE_API_RESULT_T UpdateRxDataCCCDAttribute( uint8_t ntf, uint8_t ind );
static CYBLE_API_RESULT_T UpdateAlarmsCCCDAttribute( uint8_t ntf, uint8_t ind);
static CYBLE_API_RESULT_T UpdateCyTouchErrorCCCDAttribute( uint8_t ntf, uint8_t ind );
static CYBLE_API_RESULT_T UpdateTSetCCCDAttribute(uint8_t ntf, uint8_t ind);
static CYBLE_API_RESULT_T UpdateFanSpeedCCCDAttribute(uint8_t ntf, uint8_t ind);
static CYBLE_API_RESULT_T UpdateBoostCCCDAttribute(uint8_t ntf, uint8_t ind);


void HandleBleProcess(void)
{    
    switch (cyBle_state)
    {
        case CYBLE_STATE_CONNECTED:
            
//            if(BLEStackStatus == CYBLE_STACK_STATE_BUSY) break;
//       
//            if( RxDataNotificationEnabled == NOTIFICATON_ENABLED )
//            {
                HandleUartRxTraffic();
//            } 
            break;
        case CYBLE_STATE_DISCONNECTED:
        case CYBLE_STATE_STOPPED:
        case CYBLE_STATE_ADVERTISING:
        break;
    }
}
/*******************************************************************************/


/*******************************************************************************
* Function Name: StackEvents
********************************************************************************
*
* Summary:
*   Call back function for BLE stack to handle BLESS events
*
* Parameters:
*   event       - the event generated by stack
*   eventParam  - the parameters related to the corresponding event
*
* Return: None.
*******************************************************************************/
void StackEvents(uint32 event, void *eventParam)
{
    CYBLE_GAP_AUTH_INFO_T           *authInfo;
    CYBLE_GATTS_WRITE_REQ_PARAM_T   *writeReqParam;
    CYBLE_GATT_XCHG_MTU_PARAM_T     *mtuReqParam;
    
    switch (event)
    {
        /**********************************************************
        *            General Events (0x01 - 0x1F)
        ***********************************************************/
        case CYBLE_EVT_STACK_ON:
            ( void )CyBle_GapFixAuthPassKey(true, CYTOUCH_PASS);
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            BleDataPrepareRequired = true;

            break;
        case CYBLE_EVT_STACK_BUSY_STATUS: //This event is generated when the internal stack buffer is full and no more data can be accepted or the stack has buffer available and can accept data
            BLEStackStatus = *(uint8*)eventParam; //Extract the BLE stack status
            break;
        case CYBLE_EVT_TIMEOUT:
            break;
            
        /**********************************************************
        *               GAP Events (0x02 - 0x3F)
        ***********************************************************/             
        case CYBLE_EVT_GAP_AUTH_REQ: 
            authInfo = ((CYBLE_GAP_AUTH_INFO_T *)eventParam);
            if(CyBle_GappAuthReqReply(cyBle_connHandle.bdHandle, authInfo) == CYBLE_ERROR_OK){
                
            }
            break;
        case CYBLE_EVT_GAP_PASSKEY_ENTRY_REQUEST:
//            apiResult = CyBle_GapAuthPassKeyReply(cyBle_connHandle.bdHandle, CYTOUCH_PASS, 1);
            break;
        case CYBLE_EVT_GAP_AUTH_COMPLETE:
//            authInfo = ((CYBLE_GAP_AUTH_INFO_T *)eventParam);
//            (void)authInfo;
            
            SetSoundTone(1u);
            
            ( void )CyBle_GattcExchangeMtuReq( cyBle_connHandle, CYBLE_GATT_MTU );
            ( void )CyBle_L2capLeConnectionParamUpdateRequest( cyBle_connHandle.bdHandle, &ConnectionParametersHandle );
            break;
        case CYBLE_EVT_GAP_AUTH_FAILED:
            break;
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
			if( CyBle_GetState() == CYBLE_STATE_DISCONNECTED )
			{
                CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
			}
            break;
        case CYBLE_EVT_GAP_DEVICE_CONNECTED:            
            /* Req Client to Start Authentication process */
//            apiResult = CyBle_GapAuthReq(cyBle_connHandle.bdHandle, &cyBle_authInfo);
//            AuthKeyRequired = true;
            SetSoundTone(3u);
            break;
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED: 
            SetSoundTone(3u);
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            break;   
        case CYBLE_EVT_GAP_KEYINFO_EXCHNGE_CMPLT:
            break;            
            
        /**********************************************************
        *              GATT Events (0x40 - 0x6F)
        ***********************************************************/
        case CYBLE_EVT_GATT_CONNECT_IND:           
            DeviceConnected = true; //Set device connection status flag            
            
            ( void )UpdateRxDataCCCDAttribute( NOTIFICATON_ENABLED, INDICATION_DISABLED );
            ( void )UpdateCyTouchErrorCCCDAttribute( NOTIFICATON_ENABLED, INDICATION_DISABLED );
            
            ( void )UpdateTSetCCCDAttribute( NOTIFICATON_ENABLED, INDICATION_DISABLED );
            ( void )UpdateFanSpeedCCCDAttribute( NOTIFICATON_ENABLED, INDICATION_DISABLED );
            ( void )UpdateBoostCCCDAttribute( NOTIFICATON_ENABLED, INDICATION_DISABLED );
            break;
        case CYBLE_EVT_GATT_DISCONNECT_IND:
            DeviceConnected = FALSE;        //Clear device connection status flag
           
            ( void )UpdateRxDataCCCDAttribute( NOTIFICATON_DISABLED, INDICATION_DISABLED );
            ( void )UpdateAlarmsCCCDAttribute( NOTIFICATON_DISABLED, INDICATION_DISABLED );
            ( void )UpdateCyTouchErrorCCCDAttribute( NOTIFICATON_DISABLED, INDICATION_DISABLED );
            ( void )UpdateTSetCCCDAttribute( NOTIFICATON_DISABLED, INDICATION_DISABLED );
            ( void )UpdateFanSpeedCCCDAttribute( NOTIFICATON_DISABLED, INDICATION_DISABLED );
            ( void )UpdateBoostCCCDAttribute( NOTIFICATON_DISABLED, INDICATION_DISABLED );
            
            cyBle_connHandle.bdHandle = ZERO;
            break;
        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:             
            mtuReqParam = (CYBLE_GATT_XCHG_MTU_PARAM_T *)eventParam;
            
            if( CYBLE_GATT_MTU > mtuReqParam->mtu ) mtuSize = mtuReqParam->mtu;
            else mtuSize = CYBLE_GATT_MTU;        
            break;  
        case CYBLE_EVT_GATTS_WRITE_CMD_REQ: 
            /* Extract the Write data sent by Client */
            writeReqParam = (CYBLE_GATTS_WRITE_REQ_PARAM_T *) eventParam;
            
            if( writeReqParam->handleValPair.attrHandle == CYBLE_BLEUART_TXDATA_CHAR_HANDLE )
            {            
                HandleUartTxTraffic( writeReqParam ); 
            }
            break;
        case CYBLE_EVT_GATTS_WRITE_REQ:                  
            /* Extract the Write data sent by Client */
            writeReqParam = (CYBLE_GATTS_WRITE_REQ_PARAM_T *) eventParam;              
            
            /* Nereguojam i notifikaciju ijungima / isjungima. Tik nustatom error koda */
            if( writeReqParam->handleValPair.attrHandle == CYBLE_BLEUART_RXDATA_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE ||
                writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_TSET_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE ||
                writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_FANSPEED_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE ||
                writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_BOOST_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE )
            {             
                apiResult = CYBLE_ERROR_INVALID_PARAMETER;
            }                        

    		/* Ijungiam / isjungiam Alarm pranesimus (notifikacijos) */
            if( writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_ALARMS_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE )
            {             
                /* Set Alarms notification flag so that application can start sending notifications */
                apiResult = UpdateAlarmsCCCDAttribute( 
                    writeReqParam->handleValPair.value.val[NTF_FLAG],
                    writeReqParam->handleValPair.value.val[IND_FLAG]
                );
            }
           

            /* Charakteristiku rasymas is PEER devaiso i GATT db */   
            /************************************ CHARAKTERISTIKOS **************************************/
            
            if( writeReqParam->handleValPair.attrHandle == CYBLE_BLEUART_PORTSETTINGS_CHAR_HANDLE )
            {
                /*  */
                static union{
                    uint8_t     data[4];
                    uint32_t    val;
                }baudrate;
                
                ChangeUartSettingsRequired = true;
                
                baudrate.data[0] = writeReqParam->handleValPair.value.val[0];
                baudrate.data[1] = writeReqParam->handleValPair.value.val[1];
                baudrate.data[2] = writeReqParam->handleValPair.value.val[2];
                baudrate.data[3] = writeReqParam->handleValPair.value.val[3];                
                
                apiResult = UartConfig( baudrate.val, 
                    writeReqParam->handleValPair.value.val[4], 
                    writeReqParam->handleValPair.value.val[5], 
                    writeReqParam->handleValPair.value.val[6] 
                );                                
            }
            
            if( writeReqParam->handleValPair.attrHandle == CYBLE_SYSTEM_STATUS_CHAR_HANDLE )
            {             
                CyTouchControl.Sound.data[0] = writeReqParam->handleValPair.value.val[0];
                
                SetSoundVolume( CyTouchControl.Sound.Level );              

                CyTouchControl.Blank.Timeout.data[0] = writeReqParam->handleValPair.value.val[1];
                CyTouchControl.Blank.Timeout.data[1] = writeReqParam->handleValPair.value.val[2];
                CyTouchControl.Blank.MinValue.data[0] = writeReqParam->handleValPair.value.val[3];
                CyTouchControl.Blank.MinValue.data[1] = writeReqParam->handleValPair.value.val[4];
                CyTouchControl.Blank.MaxValue.data[0] = writeReqParam->handleValPair.value.val[5];
                CyTouchControl.Blank.MaxValue.data[1] = writeReqParam->handleValPair.value.val[6];                
                
                
                CyTouchControl.TSet.MinRange.valLow = writeReqParam->handleValPair.value.val[8];
                CyTouchControl.TSet.MinRange.valHigh = writeReqParam->handleValPair.value.val[9];
                
                /* Tikrinam, ar nauja minimalios temperaturos reiksme yra leistiname diapazone? */
                if((int8_t)writeReqParam->handleValPair.value.val[7] >= CyTouchControl.TSet.MinRange.valLow &&
                (int8_t)writeReqParam->handleValPair.value.val[7] <= CyTouchControl.TSet.MinRange.valHigh)
                {                
                    CyTouchControl.TSet.MinValue.val = (int8_t)writeReqParam->handleValPair.value.val[7];
                    apiResult = CYBLE_ERROR_OK;
                }
                else{
                    apiResult = CYBLE_ERROR_INVALID_PARAMETER;
                }
                
                CyTouchControl.Status.data[0] = writeReqParam->handleValPair.value.val[10];
                CyTouchControl.Status.data[1] = writeReqParam->handleValPair.value.val[11];
                
                
                if( IsDigit(writeReqParam->handleValPair.value.val[12]) && IsDigit(writeReqParam->handleValPair.value.val[13]) &&
                    IsDigit(writeReqParam->handleValPair.value.val[14]) && IsDigit(writeReqParam->handleValPair.value.val[15])
                )
                {                
                    CyTouchControl.Passwd[0] = writeReqParam->handleValPair.value.val[12];
                    CyTouchControl.Passwd[1] = writeReqParam->handleValPair.value.val[13];
                    CyTouchControl.Passwd[2] = writeReqParam->handleValPair.value.val[14];
                    CyTouchControl.Passwd[3] = writeReqParam->handleValPair.value.val[15];
                    apiResult = CYBLE_ERROR_OK;
                }
                else{
                    apiResult = CYBLE_ERROR_INVALID_PARAMETER;
                }
                
                CyTouchControl.LockTimer.data[0] = writeReqParam->handleValPair.value.val[16];
                CyTouchControl.LockTimer.data[1] = writeReqParam->handleValPair.value.val[17];
                CyTouchControl.LockTimer.data[2] = writeReqParam->handleValPair.value.val[18];
                CyTouchControl.LockTimer.data[3] = writeReqParam->handleValPair.value.val[19];
            }            
            
            if( writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_TSET_CHAR_HANDLE )
            {
                TSetUpdateRequireBit = true;                
                
				/* Tikrinam, ar nauja TSet reikme yra darbiniame diapazone? */
                if( writeReqParam->handleValPair.value.val[0] >= CyTouchControl.TSet.MinValue.val && 
                                writeReqParam->handleValPair.value.val[0] <= (CyTouchControl.TSet.MinValue.val + 15) ){ 
                                    
                    /* Skaitom is GATT Db data naujus TSet parametrus */
                    DevData.TSet.val = writeReqParam->handleValPair.value.val[0];
                    apiResult = CYBLE_ERROR_OK;
                 }  
                else{
                    apiResult = CYBLE_ERROR_INVALID_PARAMETER;
                }
            }
            
            if( writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_FANSPEED_CHAR_HANDLE )
            {
                FanSpeedUpdateRequireBit = true;
                
				/* Change the Speed */
                if( (uint8)writeReqParam->handleValPair.value.val[0] <= (3u) ){                    
                    /* Skaitom is GATT Db data nauja Fan Speed parametra */
                    DevData.Speed.val = writeReqParam->handleValPair.value.val[0]; 
                    apiResult = CYBLE_ERROR_OK;
                } 
                else{
                    apiResult = CYBLE_ERROR_INVALID_PARAMETER;
                }
            }
            
            if( writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_BOOST_CHAR_HANDLE )
            {
				/* Change the Boost */
                if( (uint8)writeReqParam->handleValPair.value.val[0] <= (1u) ){ 
                    BoostUpdateRequireBit = true;
                    
                    /* Skaitom is GATT Db data nauja Boost parametra */
                    DevData.Boost.val = writeReqParam->handleValPair.value.val[0]; 
                    DevData.Boost.Time = writeReqParam->handleValPair.value.val[3]; 
                    apiResult = CYBLE_ERROR_OK;
                }
                else{
                    apiResult = CYBLE_ERROR_INVALID_PARAMETER;
                }
            }     
            
            if( writeReqParam->handleValPair.attrHandle == CYBLE_CYTOUCH_PRVSETTINGS_CHAR_HANDLE )
            {
                PrvSettingsUpdateRequireBit = true;
                
                DevData.PrvSettings.data[0] = writeReqParam->handleValPair.value.val[0];
                DevData.PrvSettings.data[1] = writeReqParam->handleValPair.value.val[1];
            }
            
			/* Send the response to the write request received. */
            ( void )CyBle_GattsWriteRsp(writeReqParam->connHandle);   
            
            ( void )CyTouchErrorOverNotification( apiResult );
            break;   
        case CYBLE_EVT_GATTS_READ_CHAR_VAL_ACCESS_REQ:
            break;
       /***********************************************************
        *                       L2CAP Events
        ***********************************************************/            
        case CYBLE_EVT_L2CAP_CONN_PARAM_UPDATE_RSP: //This event is generated when the L2CAP connection parameter update response received
            break;
    }
}
/*******************************************************************************/



/*******************************************************************************
* Function Name: UpdateCCCDAttribute
********************************************************************************
* Summary: This function updates the notification handle status and reports 
* it to BLE component database so that it can be read by Central device.
*
* Parameters: 
*       uint32_t handle - 
*       uint8_t ntf - 
*       uint8_t ind - 
* Return: CYBLE_API_RESULT_T
********************************************************************************/
static CYBLE_API_RESULT_T UpdateCCCDAttribute(CYBLE_GATT_DB_ATTR_HANDLE_T handle, uint8_t ntf, uint8_t ind)
{ 
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    uint8_t cccd_dat[CCCD_DATA_LEN];
    
    /* If stack is not busy, then send the notification */
    if( BLEStackStatus != CYBLE_STACK_STATE_FREE ) return CYBLE_ERROR_CONTROLLER_BUSY; 
    
    cccd_dat[NTF_FLAG] = ( ntf >= 0x01 ) ? NOTIFICATON_ENABLED : NOTIFICATON_DISABLED;
    cccd_dat[IND_FLAG] = ( ind >= 0x01 ) ? INDICATION_ENABLED : INDICATION_DISABLED;
    
    apiResult = SetCharacteristicValue(handle, cccd_dat, CCCD_DATA_LEN);
   
    return apiResult;
}
/*******************************************************************************/

/*******************************************************************************
* Function Name: GetCharacteristicValue
********************************************************************************
* Summary: skaitom is GATT Db
*
* Parameters: 
*       uint32_t    handle - 
*       uint8_t     *attrValue - 
*       uint8_t     attrSize - 
* Return: CYBLE_API_RESULT_T
********************************************************************************/
CYBLE_API_RESULT_T GetCharacteristicValue(CYBLE_GATT_DB_ATTR_HANDLE_T handle, uint8_t *attrValue, uint8_t attrSize)
{
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    CYBLE_GATT_HANDLE_VALUE_PAIR_T  locHandleValuePair;
    
    locHandleValuePair.attrHandle = handle;
    locHandleValuePair.value.val = attrValue;
    locHandleValuePair.value.len = attrSize;
    
    if( CyBle_GattsReadAttributeValue( &locHandleValuePair, NULL, CYBLE_GATT_DB_LOCALLY_INITIATED) != CYBLE_GATT_ERR_NONE )
    {
        apiResult = CYBLE_ERROR_INVALID_PARAMETER;
    }
    
    return (apiResult);
}
/*******************************************************************************/

/*******************************************************************************
* Function Name: SetCharacteristicValue
********************************************************************************
* Summary: irasom i GATT Db
*
* Parameters: 
*       uint32_t    handle - 
*       uint8_t     *attrValue - 
*       uint8_t     attrSize - 
* Return: CYBLE_API_RESULT_T
********************************************************************************/
CYBLE_API_RESULT_T SetCharacteristicValue(CYBLE_GATT_DB_ATTR_HANDLE_T handle, uint8_t *attrValue, uint8_t attrSize)
{
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    CYBLE_GATT_HANDLE_VALUE_PAIR_T  locHandleValuePair;
    
    locHandleValuePair.attrHandle = handle;
    locHandleValuePair.value.val = attrValue;
    locHandleValuePair.value.len = attrSize;
    
    if( CyBle_GattsWriteAttributeValue( &locHandleValuePair, 0u, NULL, CYBLE_GATT_DB_LOCALLY_INITIATED) != CYBLE_GATT_ERR_NONE )
    {
        apiResult = CYBLE_ERROR_INVALID_PARAMETER;
    }
    
    return (apiResult);
}
/*******************************************************************************/


/*******************************************************************************
* Function Name: Notifikaciju ijungimas / isjungimas
********************************************************************************
* Summary: This function updates the notification handle status and reports 
* it to BLE component database so that it can be read by Central device.
*
* Parameters: void
* Return: CYBLE_API_RESULT_T
********************************************************************************/
static CYBLE_API_RESULT_T UpdateRxDataCCCDAttribute(uint8_t ntf, uint8_t ind)
{ 
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;

    apiResult = UpdateCCCDAttribute( CYBLE_BLEUART_RXDATA_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE, ntf, ind );
    
    if( apiResult == CYBLE_ERROR_OK )
    {
        RxDataNotificationEnabled = ( ntf ) ? NOTIFICATON_ENABLED : NOTIFICATON_DISABLED;
    };   
    
    return apiResult;
}

static CYBLE_API_RESULT_T UpdateAlarmsCCCDAttribute(uint8_t ntf, uint8_t ind)
{     
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    
    apiResult = UpdateCCCDAttribute( CYBLE_CYTOUCH_ALARMS_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE, ntf, ind );
    
    if( apiResult == CYBLE_ERROR_OK)
    {
        AlarmsNotificationEnabled = ( ntf ) ? NOTIFICATON_ENABLED : NOTIFICATON_DISABLED;
    }
   
    return apiResult;
}

static CYBLE_API_RESULT_T UpdateCyTouchErrorCCCDAttribute(uint8_t ntf, uint8_t ind)
{   
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    
    apiResult = UpdateCCCDAttribute( CYBLE_SYSTEM_CYTOUCHERROR_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE, ntf, ind );
    
    if( apiResult == CYBLE_ERROR_OK )
    {
        CyTouchErrorNotificationEnabled = ( ntf ) ? NOTIFICATON_ENABLED : NOTIFICATON_DISABLED;
    }; 

    return apiResult;
}

static CYBLE_API_RESULT_T UpdateTSetCCCDAttribute(uint8_t ntf, uint8_t ind)
{   
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    
    apiResult = UpdateCCCDAttribute( CYBLE_CYTOUCH_TSET_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE, ntf, ind );

    return apiResult;
}

static CYBLE_API_RESULT_T UpdateFanSpeedCCCDAttribute(uint8_t ntf, uint8_t ind)
{   
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    
    apiResult = UpdateCCCDAttribute( CYBLE_CYTOUCH_FANSPEED_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE, ntf, ind );

    return apiResult;
}

static CYBLE_API_RESULT_T UpdateBoostCCCDAttribute(uint8_t ntf, uint8_t ind)
{   
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    
    apiResult = UpdateCCCDAttribute( CYBLE_CYTOUCH_BOOST_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE, ntf, ind );

    return apiResult;
}
/*******************************************************************************/


/*******************************************************************************
* Function Name: CyTouchErrorOverNotification
********************************************************************************
* Summary: This function sends the CyTouchError data as BLE notification.
* It updates the notification handle with alarms data and triggers the BLE 
* component to send notification.
*
* Parameters: void
* Return: CYBLE_API_RESULT_T
********************************************************************************/
CYBLE_API_RESULT_T CyTouchErrorOverNotification( CYBLE_API_RESULT_T  apiResult )
{     
    static CYBLE_API_RESULT_T LastResult = CYBLE_ERROR_OK;
    CYBLE_GATTS_HANDLE_VALUE_NTF_T CyTouchErrorNotificationHandle; //This handle stores the alarms notification data parameters
    
    /* If stack is not busy, then send the notification */
    if( BLEStackStatus != CYBLE_STACK_STATE_FREE ) return CYBLE_ERROR_CONTROLLER_BUSY;
    
    if( LastResult != apiResult )
    {
        LastResult = apiResult;
        
        /* Update notification handle with CyTouch Error data */
    	CyTouchErrorNotificationHandle.attrHandle = CYBLE_SYSTEM_CYTOUCHERROR_CHAR_HANDLE;
    	CyTouchErrorNotificationHandle.value.val = (uint8*)(&apiResult);
    	CyTouchErrorNotificationHandle.value.len = 0x02;
    	
    	/* Send the updated handle as part of attribute for notifications */
    	apiResult = CyBle_GattsNotification(cyBle_connHandle, &CyTouchErrorNotificationHandle);
    }
    
    return apiResult;
}
/*******************************************************************************/


/*******************************************************************************
* Function Name: PrvDataOverNotification
********************************************************************************
* Summary: This function sends the TSet data as BLE notification.
* It updates the notification handle with alarms data and triggers the BLE 
* component to send notification.
*
* Parameters: void
* Return: CYBLE_API_RESULT_T
********************************************************************************/
CYBLE_API_RESULT_T PrvDataOverNotification()
{     
    CYBLE_API_RESULT_T  apiResult = CYBLE_ERROR_OK;
    CYBLE_GATTS_HANDLE_VALUE_NTF_T NotificationHandle;
    
    static uint16_t     LastAlarmsData = ( 0u );
    static uint8_t      LastTset = ( 0u );
    static uint8_t      LastSpeed = ( 0u );
    static uint8_t      LastBoostVal = ( 0u );
    static uint16_t     LastBoostCounter = ( 0u );
    
   
    /* If stack is not busy, then send the notification */
    if( BLEStackStatus != CYBLE_STACK_STATE_FREE ) return CYBLE_ERROR_CONTROLLER_BUSY;
    
    if( AlarmsNotificationEnabled && ( LastAlarmsData != DevData.Alarms.val ))
    {
        LastAlarmsData = DevData.Alarms.val;                   

    	NotificationHandle.attrHandle = CYBLE_CYTOUCH_ALARMS_CHAR_HANDLE;
    	NotificationHandle.value.val = DevData.Alarms.data;
    	NotificationHandle.value.len = sizeof(DevData.Alarms.data);
    	
    	apiResult = CyBle_GattsNotification(cyBle_connHandle, &NotificationHandle);
    }
    
    if( DevData.TSet.val != LastTset )
    {   
        LastTset = DevData.TSet.val;

    	NotificationHandle.attrHandle = CYBLE_CYTOUCH_TSET_CHAR_HANDLE;
    	NotificationHandle.value.val = DevData.TSet.data;
    	NotificationHandle.value.len = sizeof(DevData.TSet.data);
    	
    	apiResult = CyBle_GattsNotification(cyBle_connHandle, &NotificationHandle); 
        
        BlStartTimeout();
    }
    
    if( DevData.Speed.val != LastSpeed )
    {   
        LastSpeed = DevData.Speed.val;

    	NotificationHandle.attrHandle = CYBLE_CYTOUCH_FANSPEED_CHAR_HANDLE;
    	NotificationHandle.value.val = DevData.Speed.data;
    	NotificationHandle.value.len = sizeof(DevData.Speed.data);
    	
    	apiResult = CyBle_GattsNotification(cyBle_connHandle, &NotificationHandle); 
        
        BlStartTimeout();
    }
    
    if( DevData.Boost.val != LastBoostVal || DevData.Boost.Counter != LastBoostCounter )
    {   
        LastBoostVal = DevData.Boost.val;
        LastBoostCounter = DevData.Boost.Counter;

    	NotificationHandle.attrHandle = CYBLE_CYTOUCH_BOOST_CHAR_HANDLE;
    	NotificationHandle.value.val = DevData.Boost.data;
    	NotificationHandle.value.len = sizeof(DevData.Boost.data);
    	
    	apiResult = CyBle_GattsNotification(cyBle_connHandle, &NotificationHandle);
        
        BlStartTimeout();
    }    
   
    return apiResult;
}
/*******************************************************************************/



CYBLE_API_RESULT_T DebugDataOverNotification()
{  
    CYBLE_API_RESULT_T  apiResult = CYBLE_ERROR_OK;
    CYBLE_GATTS_HANDLE_VALUE_NTF_T NotificationHandle;
    
    static uint8_t      LastQueueTail = ( 0u ); 
    
    uint8_t tail = QueueGetTail();
    
    if( tail != LastQueueTail )
    {   
        LastQueueTail = tail;

    	NotificationHandle.attrHandle = CYBLE_DEBUG_QUEUE_CHAR_HANDLE;
    	NotificationHandle.value.val = &tail;
    	NotificationHandle.value.len = sizeof( tail );
    	
    	apiResult = CyBle_GattsNotification(cyBle_connHandle, &NotificationHandle); 

        BlStartTimeout();
    }

	NotificationHandle.attrHandle = CYBLE_DEBUG_SLAVEDATA_CHAR_HANDLE;
	NotificationHandle.value.val = (uint8_t*)&prv->Status.data;
	NotificationHandle.value.len = sizeof( prv->Status.data );
	
	apiResult = CyBle_GattsNotification(cyBle_connHandle, &NotificationHandle);

    return apiResult;  
}


/*******************************************************************************
* Function Name: UpdateAllCharacteristic
********************************************************************************
* Summary: Si funkcija skaito charakteristikos is GATT Db
*
* Parameters: void
* Return: CYBLE_API_RESULT_T
********************************************************************************/
CYBLE_API_RESULT_T UpdateAllCharacteristics()
{
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;      
    
    /* If stack is not busy, then send the notification */
    if( BLEStackStatus != CYBLE_STACK_STATE_FREE ) return CYBLE_ERROR_CONTROLLER_BUSY;
    
    /* kintamosios -> GATT Db */
    ( void )SetCharacteristicValue( CYBLE_BLEUART_PORTSETTINGS_CHAR_HANDLE, MbPort.Settings.data, sizeof( MbPort.Settings.data ) );    
    
    ( void )SetCharacteristicValue( CYBLE_SYSTEM_STATUS_CHAR_HANDLE, CyTouchControl.data, sizeof(CyTouchControl.data) );

    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_SLAVEID_CHAR_HANDLE, prv->Buffers.SlaveId->data, sizeof(prv->Buffers.SlaveId->data) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_ALARMS_CHAR_HANDLE, DevData.Alarms.data, sizeof(DevData.Alarms.data) ); 
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_TSET_CHAR_HANDLE, DevData.TSet.data, sizeof(DevData.TSet.data) );  
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_TEMPSENSORS_CHAR_HANDLE, DevData.Sensors.data, sizeof(DevData.Sensors.data) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_FANSPEED_CHAR_HANDLE, DevData.Speed.data, sizeof(DevData.Speed.data) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_BOOST_CHAR_HANDLE, DevData.Boost.data, sizeof(DevData.Boost.data) );
    ( void )SetCharacteristicValue( CYBLE_SYSTEM_CYTOUCHERROR_CHAR_HANDLE, (uint8_t*)(&apiResult), sizeof(apiResult) );
    ( void )SetCharacteristicValue( CYBLE_SYSTEM_TEMPSENSOR_CHAR_HANDLE, AdcData.temperature.data, sizeof(AdcData.temperature.val) );
    
    ( void )SetCharacteristicValue (CYBLE_CYTOUCH_PRVSETTINGS_CHAR_HANDLE, DevData.PrvSettings.data, sizeof(DevData.PrvSettings.data));    
    
    ( void )SetCharacteristicValue( CYBLE_SYSTEM_SYSTICK_CHAR_HANDLE, (uint8_t*)(&Time.WTime), sizeof(Time.WTime) );
    
    return apiResult;
}
/*******************************************************************************/


/*******************************************************************************
* Function Name: BleDataPrepare
********************************************************************************
* Summary: Si funkcija uzpildo programos duomenys is GATT Db
*
* Parameters: void
* Return: CYBLE_API_RESULT_T
********************************************************************************/
CYBLE_API_RESULT_T BleDataPrepare()
{
    CYBLE_API_RESULT_T apiResult = CYBLE_ERROR_OK;
    
    BleDataPrepareRequired = FALSE;
    
    /* GATT Db -> kintamosios */    
//    ( void )GetCharacteristicValue( CYBLE_CYTOUCH_CONTROL_TSET_DESC_HANDLE, CyTouchControl.Desc.TSet.data, sizeof( CyTouchControl.Desc.TSet.data ) ); 
//    ( void )GetCharacteristicValue( CYBLE_CYTOUCH_CONTROL_PASSWORD_DESC_HANDLE, CyTouchControl.Desc.Passwd, sizeof( CyTouchControl.Desc.Passwd ) );
    
    /* kintamosios -> GATT Db */   
    // skaitom porto duomenys
    ( void )SetCharacteristicValue( CYBLE_BLEUART_PORTSETTINGS_CHAR_HANDLE, MbPort.Settings.data, sizeof( MbPort.Settings.data ) );
    
    
    // skaitom pulto duomenys
//    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_STATUS_CHAR_HANDLE, CyTouchControl.Char.data, sizeof( CyTouchControl.Char.data ) );

    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_SLAVEID_CHAR_HANDLE, prv->Buffers.SlaveId->data, sizeof(prv->Buffers.SlaveId->data) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_TSET_CHAR_HANDLE, DevData.TSet.data, sizeof( DevData.TSet.data ) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_FANSPEED_CHAR_HANDLE, DevData.Speed.data, sizeof( DevData.Speed.data ) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_BOOST_CHAR_HANDLE, DevData.Boost.data, sizeof( DevData.Boost.data ) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_ALARMS_CHAR_HANDLE, DevData.Alarms.data, sizeof( DevData.Alarms.data ) );
    ( void )SetCharacteristicValue( CYBLE_CYTOUCH_TEMPSENSORS_CHAR_HANDLE, DevData.Sensors.data, sizeof( DevData.Sensors.data ) );
    
    ( void )CyBle_DissSetCharacteristicValue(CYBLE_DIS_MANUFACTURER_NAME, sizeof(CyTouchInfo.Manufacture), (uint8*)CyTouchInfo.Manufacture);
    ( void )CyBle_DissSetCharacteristicValue(CYBLE_DIS_MODEL_NUMBER, sizeof(CyTouchInfo.Model), (uint8*)CyTouchInfo.Model);
    ( void )CyBle_DissSetCharacteristicValue(CYBLE_DIS_SERIAL_NUMBER, sizeof(CyTouchInfo.Serial), (uint8*)CyTouchInfo.Serial);
    ( void )CyBle_DissSetCharacteristicValue(CYBLE_DIS_HARDWARE_REV, sizeof(CyTouchInfo.HW), (uint8*)CyTouchInfo.HW);
    ( void )CyBle_DissSetCharacteristicValue(CYBLE_DIS_SOFTWARE_REV, sizeof(CyTouchInfo.SW), (uint8*)CyTouchInfo.SW);
    
    return apiResult;
}

/* [] END OF FILE */
